# Generated by Django 4.2.7 on 2023-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_centre', models.CharField(max_length=20)),
                ('nom_centre', models.CharField(max_length=50)),
                ('ville_centre', models.CharField(max_length=100)),
                ('district_centre', models.CharField(max_length=100)),
                ('commune_centre', models.CharField(max_length=100)),
                ('adresse_centre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Parti_politique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=50)),
                ('sigle', models.CharField(max_length=50)),
                ('autorite', models.CharField(max_length=50)),
                ('arrete', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regroupement_politiuqe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sigle', models.CharField(max_length=50)),
                ('autorite', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('adresse_physique', models.CharField(max_length=50)),
            ],
        ),
    ]
