# Generated by Django 4.2.7 on 2023-12-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_candidats_centre_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidats',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidats/photos/'),
        ),
    ]
